### PR TITLE
Docs: Example was wrong or outdated

### PR DESCRIPTION
**Pull request by jscissr**
Possibly the text underneath should be updated as well, but I don't really know (how).

### CODE REVIEW

**Comment by notwaldorf** [comment]
@jscissr Thanks for the fix! Would you mind making the same change in `README.md` as well, please? Thanks!

**Comment by notwaldorf** [comment]
@jscissr Actually, while you're at there: the `README.md` has fallen behind the `.html` altogether, so if you could replace its contents with those in `iron-autogrow-textarea.html` it would be aces :) 🎈🎉

**Comment by jscissr** [comment]
Couldn't you let the elements catalog / iron-component-page read from README instead of having it duplicated in the html file?

**Comment by jscissr** [comment]
And while *you*'re at this, could you also merge some of [my other pull requests](https://github.com/pulls?utf8=✓&q=is%3Aopen+is%3Apr+author%3Ajscissr), please? :+1: :wink:

**Comment by notwaldorf** [comment]
@jscissr Yes, we're working on sorting out the readme files, but that's not really ready yet.

Thanks for the fix. I'll look at the other PRs :)

**Comment by jscissr** [comment]
Thank you!

**Pull request merged**
