### PR TITLE
Allow users to style the internal textarea via CSS mixin

### PR DESCRIPTION
**Pull request by jimsimon**

### CODE REVIEW

**Comment by jimsimon** [comment]
Sorry for the PR spam.  I accidentally committed as the wrong user/account and the CLA bot was not happy.  It should be all squared away now.

**Comment by notwaldorf** [comment]
@jimsimon I think this would be better as a mixin. Could you replace the custom property with an `@apply(--iron-autogrow-textarea)` mixin, and document it in the header (like we do in `paper-input-container`, for example)? That way if somebody want to style something other than the padding (like, say, the border), we don't have to do a back and forth with custom properties. Thanks!

**Comment by jimsimon** [comment]
Sure thing!  I've updated the code per your recommendation.  Thanks!

**Comment by notwaldorf** [comment]
Thanks!

**Pull request merged**
